services:
  nginx:
    image: ubuntu:latest
    container_name: nginx_servers
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  test:
    image: python:3.12-alpine
    container_name: test_servers
    mem_limit: 2g
    mem_reservation: 1g
    build:
      context: ./test
      dockerfile: Dockerfile
    volumes:
      - ./test-results:/test-results
    depends_on:
      - nginx