services:
  nginx:
    container_name: nginx_servers
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  test:
    container_name: test_servers
    build:
      context: ./test
      dockerfile: Dockerfile
    entrypoint: sleep 20
    depends_on:
      - nginx