name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run the Docker containers
      run: |
        docker compose up -d

    - name: Run tests inside the test container
      run: |
        docker compose exec test python3 test.py

    - name: Copy test result from container to runner
      run: >
        docker compose cp test:app/succeeded ./succeeded || 
        docker compose cp test:app/fail ./fail

    - name: Upload result artifact
      uses: actions/upload-artifact@v4
      with:
        name: tests-result
        path: |
          succeeded
          fail
