name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Build and run the Docker containers
    - name: Build and run the Docker containers
      run: |
        docker compose build
        docker compose up -d

    # Run tests inside the 'test' container
    - name: Run tests inside the test container
      run: |
        docker compose exec test python3 test.py

    # Check test result and create artifact
    - name: Check test result and create artifact
      run: |
        if docker compose exec test test -f succeeded; then
          echo "Test passed!" > succeeded
        else
          echo "Test failed!" > fail
        fi

    # Upload result artifact
    - name: Upload result artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          /app/succeeded
          /app/fail
