name: Build and Test Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and run the Docker containers
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run tests
      run: |
        docker-compose exec test python3 /app/test.py

    - name: Check test result and create artifact
      run: |
        if [ -f /app/succeeded ]; then
          echo "Test passed" > /app/succeeded
        else
          echo "Test failed" > /app/fail
        fi

    - name: Upload result artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: /app/succeeded
