name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Build and run the Docker containers
    - name: Build and run the Docker containers
      run: |
        docker compose build
        docker compose up -d

    # Create a directory for test results
    - name: Create results directory
      run: mkdir -p test-results
      
    # Run tests and save results directly to host machine
    - name: Run tests
      run: |
        docker compose exec -T test python3 /app/test.py
        if [ $? -eq 0 ]; then
          echo "Test passed!" > test-results/succeeded
        else
          echo "Test failed!" > test-results/fail
        fi
      
    # Upload result artifact
    - name: Upload result artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
